### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Werner1201** [Werner1201/WernersPortifolio#1]
- [ ] Construir o Corpo da Página com um Carrossel
- [ ] Linkar o Controle do Carrossel com os Links do NavBar
- [ ] Tentar Construir um Meio de Mostrar em um dos Carrosseis os Projetos do GitHub usando sua API
- [ ] Fazer um ícone de E-mail e um para Whatsapp. 

- [ ] Fazer uma página de Sobre Mim.

**Comment by Werner1201** [comment]
É necessário me aprofundar em que tipo de conteúdo eu quero passar no carousel. 
É preciso também decidir o que devo escrever na página sobre mim, devo criar algo que pareça uma página estática e depois criar algo como um blog caso eu crie um backend para esse projeto ?
Devo mostrar 1 projeto em um dos Slides do Carousel ou devo mostrar meu Repositório utilizando minha foto e Nome nessa Plataforma?
